# Generated by Django 4.2.7 on 2025-06-01 23:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '0002_remove_paiement_created_at_remove_paiement_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='orders.commande', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='datePaiement',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date du paiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methodePaiement',
            field=models.CharField(choices=[('card', 'Carte bancaire'), ('cash', 'Espèces'), ('online', 'Paiement en ligne'), ('check', 'Chèque'), ('voucher', 'Bon de réduction')], max_length=10, verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statutPaiement',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=15, verbose_name='Statut du paiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='transactionId',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transaction'),
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remboursement_id', models.CharField(default='92035502-c0d0-42c1-9ba0-b797c4a02ba1', max_length=100, unique=True, verbose_name='ID Remboursement')),
                ('montant_rembourse', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant remboursé')),
                ('raison', models.TextField(verbose_name='Raison du remboursement')),
                ('statut_remboursement', models.CharField(choices=[('pending', 'En attente'), ('processed', 'Traité'), ('failed', 'Échoué')], default='pending', max_length=15, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('paiement_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='payments.paiement', verbose_name='Paiement original')),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
                'db_table': 'remboursement',
                'ordering': ['-created_at'],
            },
        ),
    ]
