# Generated by Django 4.2.7 on 2025-06-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paiement_commande_alter_paiement_datepaiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remboursement',
            name='remboursement_id',
            field=models.CharField(default='b4217ad8-89ff-4b0f-a162-8dbcdb2cf0af', max_length=100, unique=True, verbose_name='ID Remboursement'),
        ),
    ]
