# Generated by Django 4.2.7 on 2025-06-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_remboursement_remboursement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remboursement',
            name='remboursement_id',
            field=models.CharField(default='87d98384-21f5-4c53-9e6c-ba1528cf61d6', max_length=100, unique=True, verbose_name='ID Remboursement'),
        ),
    ]
