# Generated by Django 4.2.7 on 2025-06-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_remboursement_remboursement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remboursement',
            name='remboursement_id',
            field=models.CharField(default='13097507-bf04-499e-8bb1-dcd47a8a2c50', max_length=100, unique=True, verbose_name='ID Remboursement'),
        ),
    ]
