# Generated by Django 4.2.7 on 2025-06-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_remboursement_remboursement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remboursement',
            name='remboursement_id',
            field=models.CharField(default='6c36db72-2d52-4416-a386-7e8c90d56a60', max_length=100, unique=True, verbose_name='ID Remboursement'),
        ),
    ]
