# Generated by Django 4.2.7 on 2025-06-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_remboursement_remboursement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remboursement',
            name='remboursement_id',
            field=models.CharField(default='00e6143e-e653-4e03-96cc-0f1918983a49', max_length=100, unique=True, verbose_name='ID Remboursement'),
        ),
    ]
