# Generated by Django 4.2.7 on 2025-06-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_remboursement_remboursement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remboursement',
            name='remboursement_id',
            field=models.CharField(default='d7e896ed-b31d-4c32-b042-83445511a349', max_length=100, unique=True, verbose_name='ID Remboursement'),
        ),
    ]
