# Generated by Django 4.2.7 on 2025-06-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_remboursement_remboursement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remboursement',
            name='remboursement_id',
            field=models.CharField(default='9d2a64d3-b445-4b17-b6b3-41b06b26a740', max_length=100, unique=True, verbose_name='ID Remboursement'),
        ),
    ]
